import React, { useState } from "react";
import { fetchRecipes } from "../utils/api";
import RecipeTree from "./RecipeTree";
import StatsPanel from "./StatsPanel";
import Select from 'react-select';

const RecipeForm = ({ setResult }) => {
  const [target, setTarget] = useState(null);  // Single category selected
  const [algo, setAlgo] = useState("bfs");  // Defaultnya BFS
  const [mode, setMode] = useState("single");
  const [max, setMax] = useState(3);
  const [error, setError] = useState(null);
  const [recipeData, setRecipeDataState] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!target) {
      setError("Masukin dulu targetnya!");
      return;
    }

    try {
      const response = await fetchRecipes(target, algo, mode, max);
      setRecipeDataState(response);
      setResult(response);
      setError(null);
    } catch (err) {
      setError("An error occurred while fetching the recipe.");
    }
  };

  const handleToggleChange = () => {
    setMode((prevMode) => (prevMode === "multiple" ? "single" : "multiple"));
  };

  // Function to handle algorithm button selection
  const handleAlgoClick = (algorithm) => {
    setAlgo(algorithm);
  };

  const categoryOptions = [
    {value: "Acid rain", label: "Acid rain"},
    {value: "Air", label: "Air"},
    {value: "Airplane", label: "Airplane"},
    {value: "Alarm clock", label: "Alarm clock"},
    {value: "Alchemist", label: "Alchemist"},
    {value: "Alcohol", label: "Alcohol"},
    {value: "Algae", label: "Algae"},
    {value: "Alien", label: "Alien"},
    {value: "Allergy", label: "Allergy"},
    {value: "Alligator", label: "Alligator"},
    {value: "Alpaca", label: "Alpaca"},
    {value: "Ambulance", label: "Ambulance"},
    {value: "Angel", label: "Angel"},
    {value: "Angler", label: "Angler"},
    {value: "Animal", label: "Animal"},
    {value: "Ant", label: "Ant"},
    {value: "Ant farm", label: "Ant farm"},
    {value: "Antarctica", label: "Antarctica"},
    {value: "Anthill", label: "Anthill"},
    {value: "Apron", label: "Apron"},
    {value: "Aquarium", label: "Aquarium"},
    {value: "Archeologist", label: "Archeologist"},
    {value: "Archipelago", label: "Archipelago"},
    {value: "Arctic", label: "Arctic"},
    {value: "Armadillo", label: "Armadillo"},
    {value: "Armor", label: "Armor"},
    {value: "Arrow", label: "Arrow"},
    {value: "Ash", label: "Ash"},
    {value: "Astronaut", label: "Astronaut"},
    {value: "Astronomer", label: "Astronomer"},
    {value: "Atmosphere", label: "Atmosphere"},
    {value: "Atomic bomb", label: "Atomic bomb"},
    {value: "Aurora", label: "Aurora"},
    {value: "Avalanche", label: "Avalanche"},
    {value: "Aviary", label: "Aviary"},
    {value: "Axe", label: "Axe"},
    {value: "Bacon", label: "Bacon"},
    {value: "Bacteria", label: "Bacteria"},
    {value: "Baker", label: "Baker"},
    {value: "Bakery", label: "Bakery"},
    {value: "Banana", label: "Banana"},
    {value: "Banana bread", label: "Banana bread"},
    {value: "Bandage", label: "Bandage"},
    {value: "Bank", label: "Bank"},
    {value: "Barn", label: "Barn"},
    {value: "Barrel", label: "Barrel"},
    {value: "Bat", label: "Bat"},
    {value: "Batter", label: "Batter"},
    {value: "Battery", label: "Battery"},
    {value: "Bayonet", label: "Bayonet"},
    {value: "Bbq", label: "Bbq"},
    {value: "Beach", label: "Beach"},
    {value: "Beaver", label: "Beaver"},
    {value: "Bee", label: "Bee"},
    {value: "Beehive", label: "Beehive"},
    {value: "Beekeeper", label: "Beekeeper"},
    {value: "Beer", label: "Beer"},
    {value: "Bell", label: "Bell"},
    {value: "Bicycle", label: "Bicycle"},
    {value: "Big", label: "Big"},
    {value: "Binoculars", label: "Binoculars"},
    {value: "Bird", label: "Bird"},
    {value: "Birdcage", label: "Birdcage"},
    {value: "Birdhouse", label: "Birdhouse"},
    {value: "Black hole", label: "Black hole"},
    {value: "Blade", label: "Blade"},
    {value: "Blender", label: "Blender"},
    {value: "Blizzard", label: "Blizzard"},
    {value: "Blood", label: "Blood"},
    {value: "Blood bag", label: "Blood bag"},
    {value: "Boat", label: "Boat"},
    {value: "Boiler", label: "Boiler"},
    {value: "Bone", label: "Bone"},
    {value: "Bonsai tree", label: "Bonsai tree"},
    {value: "Book", label: "Book"},
    {value: "Bottle", label: "Bottle"},
    {value: "Boulder", label: "Boulder"},
    {value: "Bow", label: "Bow"},
    {value: "Box", label: "Box"},
    {value: "Bread", label: "Bread"},
    {value: "Brick", label: "Brick"},
    {value: "Bridge", label: "Bridge"},
    {value: "Broom", label: "Broom"},
    {value: "Bucket", label: "Bucket"},
    {value: "Bullet", label: "Bullet"},
    {value: "Bulletproof vest", label: "Bulletproof vest"},
    {value: "Bus", label: "Bus"},
    {value: "Butcher", label: "Butcher"},
    {value: "Butter", label: "Butter"},
    {value: "Butterfly", label: "Butterfly"},
    {value: "Butterfly net", label: "Butterfly net"},
    {value: "Cable car", label: "Cable car"},
    {value: "Cactus", label: "Cactus"},
    {value: "Cage", label: "Cage"},
    {value: "Cake", label: "Cake"},
    {value: "Camel", label: "Camel"},
    {value: "Campfire", label: "Campfire"},
    {value: "Candle", label: "Candle"},
    {value: "Candy cane", label: "Candy cane"},
    {value: "Cannon", label: "Cannon"},
    {value: "Canvas", label: "Canvas"},
    {value: "Car", label: "Car"},
    {value: "Caramel", label: "Caramel"},
    {value: "Carbon dioxide", label: "Carbon dioxide"},
    {value: "Carrot", label: "Carrot"},
    {value: "Cart", label: "Cart"},
    {value: "Cashmere", label: "Cashmere"},
    {value: "Castle", label: "Castle"},
    {value: "Cat", label: "Cat"},
    {value: "Catnip", label: "Catnip"},
    {value: "Cauldron", label: "Cauldron"},
    {value: "Cave", label: "Cave"},
    {value: "Caviar", label: "Caviar"},
    {value: "Centaur", label: "Centaur"},
    {value: "Cereal", label: "Cereal"},
    {value: "Chain", label: "Chain"},
    {value: "Chainsaw", label: "Chainsaw"},
    {value: "Chameleon", label: "Chameleon"},
    {value: "Charcoal", label: "Charcoal"},
    {value: "Cheese", label: "Cheese"},
    {value: "Cheeseburger", label: "Cheeseburger"},
    {value: "Chicken", label: "Chicken"},
    {value: "Chicken coop", label: "Chicken coop"},
    {value: "Chicken soup", label: "Chicken soup"},
    {value: "Chicken wing", label: "Chicken wing"},
    {value: "Chill", label: "Chill"},
    {value: "Chimney", label: "Chimney"},
    {value: "Chocolate", label: "Chocolate"},
    {value: "Chocolate milk", label: "Chocolate milk"},
    {value: "Christmas stocking", label: "Christmas stocking"},
    {value: "Christmas tree", label: "Christmas tree"},
    {value: "Cigarette", label: "Cigarette"},
    {value: "Circus", label: "Circus"},
    {value: "City", label: "City"},
    {value: "Clay", label: "Clay"},
    {value: "Clock", label: "Clock"},
    {value: "Closet", label: "Closet"},
    {value: "Cloud", label: "Cloud"},
    {value: "Coal", label: "Coal"},
    {value: "Coconut", label: "Coconut"},
    {value: "Coconut milk", label: "Coconut milk"},
    {value: "Coffin", label: "Coffin"},
    {value: "Cold", label: "Cold"},
    {value: "Combustion engine", label: "Combustion engine"},
    {value: "Computer", label: "Computer"},
    {value: "Computer mouse", label: "Computer mouse"},
    {value: "Confetti", label: "Confetti"},
    {value: "Constellation", label: "Constellation"},
    {value: "Container", label: "Container"},
    {value: "Continent", label: "Continent"},
    {value: "Cook", label: "Cook"},
    {value: "Cookbook", label: "Cookbook"},
    {value: "Cookie", label: "Cookie"},
    {value: "Cookie cutter", label: "Cookie cutter"},
    {value: "Cookie dough", label: "Cookie dough"},
    {value: "Coral", label: "Coral"},
    {value: "Corpse", label: "Corpse"},
    {value: "Cotton", label: "Cotton"},
    {value: "Cotton candy", label: "Cotton candy"},
    {value: "Cow", label: "Cow"},
    {value: "Crayon", label: "Crayon"},
    {value: "Crow", label: "Crow"},
    {value: "Crystal ball", label: "Crystal ball"},
    {value: "Cuckoo", label: "Cuckoo"},
    {value: "Cup", label: "Cup"},
    {value: "Current", label: "Current"},
    {value: "Cutting board", label: "Cutting board"},
    {value: "Cyborg", label: "Cyborg"},
    {value: "Cyclist", label: "Cyclist"},
    {value: "Dam", label: "Dam"},
    {value: "Darkness", label: "Darkness"},
    {value: "Dawn", label: "Dawn"},
    {value: "Day", label: "Day"},
    {value: "Death", label: "Death"},
    {value: "Desert", label: "Desert"},
    {value: "Dew", label: "Dew"},
    {value: "Diamond", label: "Diamond"},
    {value: "Dinosaur", label: "Dinosaur"},
    {value: "Diver", label: "Diver"},
    {value: "Doctor", label: "Doctor"},
    {value: "Dog", label: "Dog"},
    {value: "Doge", label: "Doge"},
    {value: "Doghouse", label: "Doghouse"},
    {value: "Domestication", label: "Domestication"},
    {value: "Don quixote", label: "Don quixote"},
    {value: "Donut", label: "Donut"},
    {value: "Double rainbow!", label: "Double rainbow!"},
    {value: "Dough", label: "Dough"},
    {value: "Dragon", label: "Dragon"},
    {value: "Drone", label: "Drone"},
    {value: "Drum", label: "Drum"},
    {value: "Drunk", label: "Drunk"},
    {value: "Dry ice", label: "Dry ice"},
    {value: "Duck", label: "Duck"},
    {value: "Duckling", label: "Duckling"},
    {value: "Dune", label: "Dune"},
    {value: "Dust", label: "Dust"},
    {value: "Dynamite", label: "Dynamite"},
    {value: "Eagle", label: "Eagle"},
    {value: "Earth", label: "Earth"},
    {value: "Earthquake", label: "Earthquake"},
    {value: "Eclipse", label: "Eclipse"},
    {value: "Egg", label: "Egg"},
    {value: "Egg timer", label: "Egg timer"},
    {value: "Electric car", label: "Electric car"},
    {value: "Electric eel", label: "Electric eel"},
    {value: "Electrician", label: "Electrician"},
    {value: "Electricity", label: "Electricity"},
    {value: "Email", label: "Email"},
    {value: "Energy", label: "Energy"},
    {value: "Engineer", label: "Engineer"},
    {value: "Eruption", label: "Eruption"},
    {value: "Excalibur", label: "Excalibur"},
    {value: "Excavator", label: "Excavator"},
    {value: "Explosion", label: "Explosion"},
    {value: "Fabric", label: "Fabric"},
    {value: "Factory", label: "Factory"},
    {value: "Fairy tale", label: "Fairy tale"},
    {value: "Family", label: "Family"},
    {value: "Family tree", label: "Family tree"},
    {value: "Farm", label: "Farm"},
    {value: "Farmer", label: "Farmer"},
    {value: "Faun", label: "Faun"},
    {value: "Fence", label: "Fence"},
    {value: "Field", label: "Field"},
    {value: "Fire", label: "Fire"},
    {value: "Fire extinguisher", label: "Fire extinguisher"},
    {value: "Firefighter", label: "Firefighter"},
    {value: "Fireplace", label: "Fireplace"},
    {value: "Firestation", label: "Firestation"},
    {value: "Firetruck", label: "Firetruck"},
    {value: "Firewall", label: "Firewall"},
    {value: "Fireworks", label: "Fireworks"},
    {value: "Fish", label: "Fish"},
    {value: "Fishing rod", label: "Fishing rod"},
    {value: "Flamethrower", label: "Flamethrower"},
    {value: "Flashlight", label: "Flashlight"},
    {value: "Flood", label: "Flood"},
    {value: "Flour", label: "Flour"},
    {value: "Flower", label: "Flower"},
    {value: "Flute", label: "Flute"},
    {value: "Flying fish", label: "Flying fish"},
    {value: "Flying squirrel", label: "Flying squirrel"},
    {value: "Fog", label: "Fog"},
    {value: "Force knight", label: "Force knight"},
    {value: "Forest", label: "Forest"},
    {value: "Fork", label: "Fork"},
    {value: "Fortune cookie", label: "Fortune cookie"},
    {value: "Fossil", label: "Fossil"},
    {value: "Fountain", label: "Fountain"},
    {value: "Fox", label: "Fox"},
    {value: "Frankenstein's monster", label: "Frankenstein's monster"},
    {value: "French fries", label: "French fries"},
    {value: "Fridge", label: "Fridge"},
    {value: "Frog", label: "Frog"},
    {value: "Frozen yogurt", label: "Frozen yogurt"},
    {value: "Fruit", label: "Fruit"},
    {value: "Fruit tree", label: "Fruit tree"},
    {value: "Galaxy", label: "Galaxy"},
    {value: "Galaxy cluster", label: "Galaxy cluster"},
    {value: "Garage", label: "Garage"},
    {value: "Garden", label: "Garden"},
    {value: "Gardener", label: "Gardener"},
    {value: "Gas", label: "Gas"},
    {value: "Geyser", label: "Geyser"},
    {value: "Ghost", label: "Ghost"},
    {value: "Gift", label: "Gift"},
    {value: "Gingerbread house", label: "Gingerbread house"},
    {value: "Gingerbread man", label: "Gingerbread man"},
    {value: "Glacier", label: "Glacier"},
    {value: "Glass", label: "Glass"},
    {value: "Glasses", label: "Glasses"},
    {value: "Gnome", label: "Gnome"},
    {value: "Goat", label: "Goat"},
    {value: "Gold", label: "Gold"},
    {value: "Golem", label: "Golem"},
    {value: "Granite", label: "Granite"},
    {value: "Grass", label: "Grass"},
    {value: "Grave", label: "Grave"},
    {value: "Gravestone", label: "Gravestone"},
    {value: "Graveyard", label: "Graveyard"},
    {value: "Greenhouse", label: "Greenhouse"},
    {value: "Grenade", label: "Grenade"},
    {value: "Grilled cheese", label: "Grilled cheese"},
    {value: "Grim reaper", label: "Grim reaper"},
    {value: "Gun", label: "Gun"},
    {value: "Gunpowder", label: "Gunpowder"},
    {value: "Gust", label: "Gust"},
    {value: "Hacker", label: "Hacker"},
    {value: "Hail", label: "Hail"},
    {value: "Ham", label: "Ham"},
    {value: "Hamburger", label: "Hamburger"},
    {value: "Hammer", label: "Hammer"},
    {value: "Hamster", label: "Hamster"},
    {value: "Hangar", label: "Hangar"},
    {value: "Harp", label: "Harp"},
    {value: "Hay", label: "Hay"},
    {value: "Hay bale", label: "Hay bale"},
    {value: "Heat", label: "Heat"},
    {value: "Hedge", label: "Hedge"},
    {value: "Hedgehog", label: "Hedgehog"},
    {value: "Helicopter", label: "Helicopter"},
    {value: "Hero", label: "Hero"},
    {value: "Hill", label: "Hill"},
    {value: "Hippo", label: "Hippo"},
    {value: "Honey", label: "Honey"},
    {value: "Horizon", label: "Horizon"},
    {value: "Horse", label: "Horse"},
    {value: "Horseshoe", label: "Horseshoe"},
    {value: "Hospital", label: "Hospital"},
    {value: "Hot chocolate", label: "Hot chocolate"},
    {value: "Hourglass", label: "Hourglass"},
    {value: "House", label: "House"},
    {value: "Human", label: "Human"},
    {value: "Hummingbird", label: "Hummingbird"},
    {value: "Hurricane", label: "Hurricane"},
    {value: "Husky", label: "Husky"},
    {value: "Ice", label: "Ice"},
    {value: "Ice cream", label: "Ice cream"},
    {value: "Ice cream truck", label: "Ice cream truck"},
    {value: "Ice sculpture", label: "Ice sculpture"},
    {value: "Iceberg", label: "Iceberg"},
    {value: "Iced tea", label: "Iced tea"},
    {value: "Idea", label: "Idea"},
    {value: "Igloo", label: "Igloo"},
    {value: "Internet", label: "Internet"},
    {value: "Island", label: "Island"},
    {value: "Ivy", label: "Ivy"},
    {value: "Jack-o'-lantern", label: "Jack-o'-lantern"},
    {value: "Jam", label: "Jam"},
    {value: "Jar", label: "Jar"},
    {value: "Jerky", label: "Jerky"},
    {value: "Juice", label: "Juice"},
    {value: "Jupiter", label: "Jupiter"},
    {value: "Kaiju", label: "Kaiju"},
    {value: "Katana", label: "Katana"},
    {value: "Kite", label: "Kite"},
    {value: "Knife", label: "Knife"},
    {value: "Knight", label: "Knight"},
    {value: "Lake", label: "Lake"},
    {value: "Lamp", label: "Lamp"},
    {value: "Land", label: "Land"},
    {value: "Laptop", label: "Laptop"},
    {value: "Lasso", label: "Lasso"},
    {value: "Lava", label: "Lava"},
    {value: "Lava lamp", label: "Lava lamp"},
    {value: "Lawn", label: "Lawn"},
    {value: "Lawn mower", label: "Lawn mower"},
    {value: "Leaf", label: "Leaf"},
    {value: "Leather", label: "Leather"},
    {value: "Legend", label: "Legend"},
    {value: "Lens", label: "Lens"},
    {value: "Letter", label: "Letter"},
    {value: "Librarian", label: "Librarian"},
    {value: "Library", label: "Library"},
    {value: "Life", label: "Life"},
    {value: "Light", label: "Light"},
    {value: "Light bulb", label: "Light bulb"},
    {value: "Light sword", label: "Light sword"},
    {value: "Lighthouse", label: "Lighthouse"},
    {value: "Lightning", label: "Lightning"},
    {value: "Lion", label: "Lion"},
    {value: "Liquid", label: "Liquid"},
    {value: "Little alchemy (element)", label: "Little alchemy (element)"},
    {value: "Livestock", label: "Livestock"},
    {value: "Lizard", label: "Lizard"},
    {value: "Log cabin", label: "Log cabin"},
    {value: "Love", label: "Love"},
    {value: "Lumberjack", label: "Lumberjack"},
    {value: "Mac and cheese", label: "Mac and cheese"},
    {value: "Machine", label: "Machine"},
    {value: "Magic", label: "Magic"},
    {value: "Magma", label: "Magma"},
    {value: "Mail truck", label: "Mail truck"},
    {value: "Mailbox", label: "Mailbox"},
    {value: "Mailman", label: "Mailman"},
    {value: "Manatee", label: "Manatee"},
    {value: "Map", label: "Map"},
    {value: "Maple syrup", label: "Maple syrup"},
    {value: "Mars", label: "Mars"},
    {value: "Marshmallows", label: "Marshmallows"},
    {value: "Mayonnaise", label: "Mayonnaise"},
    {value: "Meat", label: "Meat"},
    {value: "Medusa", label: "Medusa"},
    {value: "Mercury", label: "Mercury"},
    {value: "Mermaid", label: "Mermaid"},
    {value: "Metal", label: "Metal"},
    {value: "Meteor", label: "Meteor"},
    {value: "Meteoroid", label: "Meteoroid"},
    {value: "Microscope", label: "Microscope"},
    {value: "Milk", label: "Milk"},
    {value: "Milk shake", label: "Milk shake"},
    {value: "Mineral", label: "Mineral"},
    {value: "Minotaur", label: "Minotaur"},
    {value: "Mirror", label: "Mirror"},
    {value: "Mist", label: "Mist"},
    {value: "Mold", label: "Mold"},
    {value: "Monarch", label: "Monarch"},
    {value: "Money", label: "Money"},
    {value: "Monkey", label: "Monkey"},
    {value: "Moon", label: "Moon"},
    {value: "Moon rover", label: "Moon rover"},
    {value: "Moss", label: "Moss"},
    {value: "Moth", label: "Moth"},
    {value: "Motion", label: "Motion"},
    {value: "Motorcycle", label: "Motorcycle"},
    {value: "Mountain", label: "Mountain"},
    {value: "Mountain goat", label: "Mountain goat"},
    {value: "Mountain range", label: "Mountain range"},
    {value: "Mouse", label: "Mouse"},
    {value: "Mousetrap", label: "Mousetrap"},
    {value: "Mud", label: "Mud"},
    {value: "Mummy", label: "Mummy"},
    {value: "Music", label: "Music"},
    {value: "Musician", label: "Musician"},
    {value: "Narwhal", label: "Narwhal"},
    {value: "Needle", label: "Needle"},
    {value: "Nessie", label: "Nessie"},
    {value: "Nest", label: "Nest"},
    {value: "Net", label: "Net"},
    {value: "Newspaper", label: "Newspaper"},
    {value: "Night", label: "Night"},
    {value: "Ninja", label: "Ninja"},
    {value: "Ninja turtle", label: "Ninja turtle"},
    {value: "Nuts", label: "Nuts"},
    {value: "Oasis", label: "Oasis"},
    {value: "Obsidian", label: "Obsidian"},
    {value: "Ocean", label: "Ocean"},
    {value: "Oil", label: "Oil"},
    {value: "Omelette", label: "Omelette"},
    {value: "Optical fiber", label: "Optical fiber"},
    {value: "Orchard", label: "Orchard"},
    {value: "Ore", label: "Ore"},
    {value: "Organic matter", label: "Organic matter"},
    {value: "Origami", label: "Origami"},
    {value: "Ostrich", label: "Ostrich"},
    {value: "Owl", label: "Owl"},
    {value: "Oxygen", label: "Oxygen"},
    {value: "Ozone", label: "Ozone"},
    {value: "Paint", label: "Paint"},
    {value: "Painter", label: "Painter"},
    {value: "Painting", label: "Painting"},
    {value: "Paleontologist", label: "Paleontologist"},
    {value: "Palm", label: "Palm"},
    {value: "Pan flute", label: "Pan flute"},
    {value: "Paper", label: "Paper"},
    {value: "Paper airplane", label: "Paper airplane"},
    {value: "Paper cup", label: "Paper cup"},
    {value: "Parachute", label: "Parachute"},
    {value: "Paraglider", label: "Paraglider"},
    {value: "Park", label: "Park"},
    {value: "Parrot", label: "Parrot"},
    {value: "Pasta", label: "Pasta"},
    {value: "Peacock", label: "Peacock"},
    {value: "Peanut butter", label: "Peanut butter"},
    {value: "Peat", label: "Peat"},
    {value: "Pebble", label: "Pebble"},
    {value: "Pegasus", label: "Pegasus"},
    {value: "Pencil", label: "Pencil"},
    {value: "Pencil sharpener", label: "Pencil sharpener"},
    {value: "Penguin", label: "Penguin"},
    {value: "Penicillin", label: "Penicillin"},
    {value: "Perfume", label: "Perfume"},
    {value: "Petroleum", label: "Petroleum"},
    {value: "Philosophy", label: "Philosophy"},
    {value: "Phoenix", label: "Phoenix"},
    {value: "Picnic", label: "Picnic"},
    {value: "Pie", label: "Pie"},
    {value: "Pig", label: "Pig"},
    {value: "Pigeon", label: "Pigeon"},
    {value: "Piggy bank", label: "Piggy bank"},
    {value: "Pilot", label: "Pilot"},
    {value: "Pinocchio", label: "Pinocchio"},
    {value: "Pipe", label: "Pipe"},
    {value: "Piranha", label: "Piranha"},
    {value: "Pirate", label: "Pirate"},
    {value: "Pirate ship", label: "Pirate ship"},
    {value: "Pitchfork", label: "Pitchfork"},
    {value: "Pizza", label: "Pizza"},
    {value: "Planet", label: "Planet"},
    {value: "Plankton", label: "Plankton"},
    {value: "Plant", label: "Plant"},
    {value: "Plasma", label: "Plasma"},
    {value: "Platypus", label: "Platypus"},
    {value: "Plow", label: "Plow"},
    {value: "Polar bear", label: "Polar bear"},
    {value: "Pollen", label: "Pollen"},
    {value: "Pond", label: "Pond"},
    {value: "Popsicle", label: "Popsicle"},
    {value: "Post office", label: "Post office"},
    {value: "Potato", label: "Potato"},
    {value: "Potter", label: "Potter"},
    {value: "Pottery", label: "Pottery"},
    {value: "Pressure", label: "Pressure"},
    {value: "Primordial soup", label: "Primordial soup"},
    {value: "Printer", label: "Printer"},
    {value: "Prism", label: "Prism"},
    {value: "Pterodactyl", label: "Pterodactyl"},
    {value: "Puddle", label: "Puddle"},
    {value: "Pumpkin", label: "Pumpkin"},
    {value: "Pyramid", label: "Pyramid"},
    {value: "Quicksand", label: "Quicksand"},
    {value: "Quicksilver", label: "Quicksilver"},
    {value: "Rabbit", label: "Rabbit"},
    {value: "Rain", label: "Rain"},
    {value: "Rainbow", label: "Rainbow"},
    {value: "Rainforest", label: "Rainforest"},
    {value: "Rat", label: "Rat"},
    {value: "Recipe", label: "Recipe"},
    {value: "Reed", label: "Reed"},
    {value: "Reindeer", label: "Reindeer"},
    {value: "Restaurant", label: "Restaurant"},
    {value: "Ring", label: "Ring"},
    {value: "River", label: "River"},
    {value: "Rivulet", label: "Rivulet"},
    {value: "Robot", label: "Robot"},
    {value: "Robot vacuum", label: "Robot vacuum"},
    {value: "Rock", label: "Rock"},
    {value: "Rocket", label: "Rocket"},
    {value: "Roe", label: "Roe"},
    {value: "Roller coaster", label: "Roller coaster"},
    {value: "Rope", label: "Rope"},
    {value: "Rose", label: "Rose"},
    {value: "Ruins", label: "Ruins"},
    {value: "Ruler", label: "Ruler"},
    {value: "Rust", label: "Rust"},
    {value: "Rv", label: "Rv"},
    {value: "Sack", label: "Sack"},
    {value: "Saddle", label: "Saddle"},
    {value: "Safe", label: "Safe"},
    {value: "Safety glasses", label: "Safety glasses"},
    {value: "Sailboat", label: "Sailboat"},
    {value: "Sailor", label: "Sailor"},
    {value: "Salt", label: "Salt"},
    {value: "Samurai", label: "Samurai"},
    {value: "Sand", label: "Sand"},
    {value: "Sand castle", label: "Sand castle"},
    {value: "Sandpaper", label: "Sandpaper"},
    {value: "Sandstone", label: "Sandstone"},
    {value: "Sandstorm", label: "Sandstorm"},
    {value: "Sandwich", label: "Sandwich"},
    {value: "Santa", label: "Santa"},
    {value: "Sap", label: "Sap"},
    {value: "Saturn", label: "Saturn"},
    {value: "Scalpel", label: "Scalpel"},
    {value: "Scarecrow", label: "Scarecrow"},
    {value: "Science", label: "Science"},
    {value: "Scissors", label: "Scissors"},
    {value: "Scorpion", label: "Scorpion"},
    {value: "Scuba tank", label: "Scuba tank"},
    {value: "Scythe", label: "Scythe"},
    {value: "Sea", label: "Sea"},
    {value: "Seagull", label: "Seagull"},
    {value: "Seahorse", label: "Seahorse"},
    {value: "Seal", label: "Seal"},
    {value: "Seaplane", label: "Seaplane"},
    {value: "Seasickness", label: "Seasickness"},
    {value: "Seaweed", label: "Seaweed"},
    {value: "Seed", label: "Seed"},
    {value: "Sewing machine", label: "Sewing machine"},
    {value: "Shark", label: "Shark"},
    {value: "Sheep", label: "Sheep"},
    {value: "Sheet music", label: "Sheet music"},
    {value: "Shovel", label: "Shovel"},
    {value: "Shuriken", label: "Shuriken"},
    {value: "Sickness", label: "Sickness"},
    {value: "Silo", label: "Silo"},
    {value: "Skateboard", label: "Skateboard"},
    {value: "Skeleton", label: "Skeleton"},
    {value: "Ski goggles", label: "Ski goggles"},
    {value: "Skier", label: "Skier"},
    {value: "Sky", label: "Sky"},
    {value: "Skyscraper", label: "Skyscraper"},
    {value: "Sleigh", label: "Sleigh"},
    {value: "Sloth", label: "Sloth"},
    {value: "Small", label: "Small"},
    {value: "Smartphone", label: "Smartphone"},
    {value: "Smog", label: "Smog"},
    {value: "Smoke", label: "Smoke"},
    {value: "Smoke signal", label: "Smoke signal"},
    {value: "Smoothie", label: "Smoothie"},
    {value: "Snake", label: "Snake"},
    {value: "Snow", label: "Snow"},
    {value: "Snow globe", label: "Snow globe"},
    {value: "Snowball", label: "Snowball"},
    {value: "Snowboard", label: "Snowboard"},
    {value: "Snowboarder", label: "Snowboarder"},
    {value: "Snowman", label: "Snowman"},
    {value: "Snowmobile", label: "Snowmobile"},
    {value: "Soap", label: "Soap"},
    {value: "Soda", label: "Soda"},
    {value: "Soil", label: "Soil"},
    {value: "Solar cell", label: "Solar cell"},
    {value: "Solar system", label: "Solar system"},
    {value: "Solid", label: "Solid"},
    {value: "Sound", label: "Sound"},
    {value: "Space", label: "Space"},
    {value: "Space station", label: "Space station"},
    {value: "Spaceship", label: "Spaceship"},
    {value: "Spaghetti", label: "Spaghetti"},
    {value: "Sphinx", label: "Sphinx"},
    {value: "Spider", label: "Spider"},
    {value: "Spoon", label: "Spoon"},
    {value: "Spotlight", label: "Spotlight"},
    {value: "Sprinkles", label: "Sprinkles"},
    {value: "Squirrel", label: "Squirrel"},
    {value: "Star", label: "Star"},
    {value: "Starfish", label: "Starfish"},
    {value: "Statue", label: "Statue"},
    {value: "Steak", label: "Steak"},
    {value: "Steam", label: "Steam"},
    {value: "Steam engine", label: "Steam engine"},
    {value: "Steamboat", label: "Steamboat"},
    {value: "Steel", label: "Steel"},
    {value: "Steel wool", label: "Steel wool"},
    {value: "Stethoscope", label: "Stethoscope"},
    {value: "Stone", label: "Stone"},
    {value: "Storm", label: "Storm"},
    {value: "Story", label: "Story"},
    {value: "Stream", label: "Stream"},
    {value: "String phone", label: "String phone"},
    {value: "Stun gun", label: "Stun gun"},
    {value: "Sugar", label: "Sugar"},
    {value: "Sun", label: "Sun"},
    {value: "Sundial", label: "Sundial"},
    {value: "Sunflower", label: "Sunflower"},
    {value: "Sunglasses", label: "Sunglasses"},
    {value: "Supernova", label: "Supernova"},
    {value: "Surfer", label: "Surfer"},
    {value: "Sushi", label: "Sushi"},
    {value: "Swamp", label: "Swamp"},
    {value: "Sweater", label: "Sweater"},
    {value: "Swim goggles", label: "Swim goggles"},
    {value: "Swimmer", label: "Swimmer"},
    {value: "Swimming pool", label: "Swimming pool"},
    {value: "Sword", label: "Sword"},
    {value: "Swordfish", label: "Swordfish"},
    {value: "Syringe", label: "Syringe"},
    {value: "Tablet", label: "Tablet"},
    {value: "Tailor", label: "Tailor"},
    {value: "Tank", label: "Tank"},
    {value: "Tea", label: "Tea"},
    {value: "Telescope", label: "Telescope"},
    {value: "Tent", label: "Tent"},
    {value: "The one ring", label: "The one ring"},
    {value: "Thermometer", label: "Thermometer"},
    {value: "Thread", label: "Thread"},
    {value: "Tide", label: "Tide"},
    {value: "Titanic", label: "Titanic"},
    {value: "Toast", label: "Toast"},
    {value: "Tobacco", label: "Tobacco"},
    {value: "Tool", label: "Tool"},
    {value: "Toolbox", label: "Toolbox"},
    {value: "Tornado", label: "Tornado"},
    {value: "Toucan", label: "Toucan"},
    {value: "Tractor", label: "Tractor"},
    {value: "Train", label: "Train"},
    {value: "Trainyard", label: "Trainyard"},
    {value: "Treasure", label: "Treasure"},
    {value: "Treasure map", label: "Treasure map"},
    {value: "Tree", label: "Tree"},
    {value: "Treehouse", label: "Treehouse"},
    {value: "Trojan horse", label: "Trojan horse"},
    {value: "Tsunami", label: "Tsunami"},
    {value: "Tunnel", label: "Tunnel"},
    {value: "Turtle", label: "Turtle"},
    {value: "Twilight", label: "Twilight"},
    {value: "Tyrannosaurus rex", label: "Tyrannosaurus rex"},
    {value: "Ufo", label: "Ufo"},
    {value: "Umbrella", label: "Umbrella"},
    {value: "Unicorn", label: "Unicorn"},
    {value: "Universe", label: "Universe"},
    {value: "Vacuum cleaner", label: "Vacuum cleaner"},
    {value: "Vampire", label: "Vampire"},
    {value: "Vase", label: "Vase"},
    {value: "Vault", label: "Vault"},
    {value: "Vegetable", label: "Vegetable"},
    {value: "Venus", label: "Venus"},
    {value: "Village", label: "Village"},
    {value: "Vine", label: "Vine"},
    {value: "Vinegar", label: "Vinegar"},
    {value: "Volcano", label: "Volcano"},
    {value: "Vulture", label: "Vulture"},
    {value: "Wagon", label: "Wagon"},
    {value: "Wall", label: "Wall"},
    {value: "Wand", label: "Wand"},
    {value: "Warmth", label: "Warmth"},
    {value: "Warrior", label: "Warrior"},
    {value: "Watch", label: "Watch"},
    {value: "Water", label: "Water"},
    {value: "Water gun", label: "Water gun"},
    {value: "Water lily", label: "Water lily"},
    {value: "Water pipe", label: "Water pipe"},
    {value: "Waterfall", label: "Waterfall"},
    {value: "Wave", label: "Wave"},
    {value: "Wax", label: "Wax"},
    {value: "Web", label: "Web"},
    {value: "Werewolf", label: "Werewolf"},
    {value: "Wheat", label: "Wheat"},
    {value: "Wheel", label: "Wheel"},
    {value: "Wild boar", label: "Wild boar"},
    {value: "Wind", label: "Wind"},
    {value: "Wind turbine", label: "Wind turbine"},
    {value: "Windmill", label: "Windmill"},
    {value: "Windsurfer", label: "Windsurfer"},
    {value: "Wine", label: "Wine"},
    {value: "Wire", label: "Wire"},
    {value: "Witch", label: "Witch"},
    {value: "Wizard", label: "Wizard"},
    {value: "Wolf", label: "Wolf"},
    {value: "Wood", label: "Wood"},
    {value: "Woodpecker", label: "Woodpecker"},
    {value: "Wool", label: "Wool"},
    {value: "Wrapping paper", label: "Wrapping paper"},
    {value: "Writer", label: "Writer"},
    {value: "Yeti", label: "Yeti"},
    {value: "Yogurt", label: "Yogurt"},
    {value: "Zombie", label: "Zombie"},
    {value: "Zoo", label: "Zoo"}
  ];


  return (
    <div>
      <form onSubmit={handleSubmit}>
        <label>
          Select Category:
          <Select
            isClearable
            name="category"
            options={categoryOptions}
            onChange={(selectedOption) => setTarget(selectedOption ? selectedOption.label : null)}
            value={categoryOptions.find(option => option.label === target) || null}
            placeholder="Search and select a category"
            className="category-select"
          />
        </label>
        <br />

        <label>Algoritma:</label>
        <div>
          <button
            type="button"
            className={`algo-btn ${algo === "bfs" ? "active" : ""}`}
            onClick={() => handleAlgoClick("bfs")}
          >
            BFS
          </button>
          <button
            type="button"
            className={`algo-btn ${algo === "dfs" ? "active" : ""}`}
            onClick={() => handleAlgoClick("dfs")}
          >
            DFS
          </button>
          <button
            type="button"
            className={`algo-btn ${algo === "bidirectional" ? "active" : ""}`}
            onClick={() => handleAlgoClick("bidirectional")}
          >
            Bidirectional
          </button>
        </div>
        <br />

        <div className="toggle-container">
          <label>Multiple Recipe:</label>
          <label className="switch">
            <input
              type="checkbox"
              checked={mode === "multiple"}
              onChange={handleToggleChange}
            />
            <span className="slider"></span>
          </label>
        </div>
        <br />

        {mode === "multiple" && (
          <>
            <label>
              Max Recipes:
              <input
                type="range"
                min="1"
                max="6"
                value={max}
                onChange={(e) => setMax(e.target.value)}
                className="recipe-slider"
              />
              <span>{max}</span>
            </label>
            <br />
          </>
        )}

        <button className="btn">Search</button>
      </form>

      {error && <p style={{ color: "red" }}>{error}</p>}

      {recipeData && (
        <>
          <RecipeTree data={recipeData} />
          <StatsPanel data={recipeData} />
        </>
      )}
    </div>
  );
};

export default RecipeForm;
